### ISSUE TITLE
MyGene client: .query with fields=list returns incomplete results

### ISSUE THREAD

**Issue by dhimmel** [biothings/biothings_client.py#12]
The documentation indicates that a list is accepted for `biothings_client.MyGeneInfo`'s `fields` argument (and passing a list is certainly the most pythonic interface):

https://github.com/biothings/biothings_client.py/blob/f7b53d53a566eac4e8a9d8694b6d3865bacfeab8/biothings_client/docstring/gene.py#L7-L8

But using a list seems to result in missing fields.

## Reproducible example

```python
import biothings_client
mg = biothings_client.get_client('gene')
biothings_client.__version__
```

Using version 0.2.1.

```python
fields = [
    'entrezgene',
    'symbol',
    'name',
    'genomic_pos.chr',
]
results = mg.query(
    'type_of_gene:"protein-coding"',
    fields=", ".join(fields),  # does not work as list
    species="human",
    fetch_all=True,
    entrezonly=True,
)
next(results)
```

Outputs the expected result:

```python
{'_id': '283450',
 '_score': 0.28663203,
 'entrezgene': '283450',
 'genomic_pos': {'chr': '12'},
 'name': 'HECT domain E3 ubiquitin protein ligase 4',
 'symbol': 'HECTD4'}
```

However when fields is a list rather than a string:

```python
results = mg.query(
    'type_of_gene:"protein-coding"',
    fields=fields,  # this should work, but doesn't
    species="human",
    fetch_all=True,
    entrezonly=True,
)
next(results)
```

```python
# all fields besides genomic_pos are missing
{'_id': '283450', '_score': 0.28663203, 'genomic_pos': {'chr': '12'}}
```

**Comment by dhimmel** [comment]
Possibly related, It doesn't seem like passing a list of field names to `always_list` or `allow_null` is supported. Ideally, all options that take fields would support the same syntaxes.

**Comment by newgene** [comment]
Let's handle `always_list` or `allow_null` the  way as `fields`.

**Comment by namespacestd0** [comment]
Implemented in https://pypi.org/project/biothings-client/0.2.3/
