### ISSUE TITLE
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by dhimmel** [biothings/biothings_client.py#13]
The following line is deprecated in Python 3.8:

https://github.com/biothings/biothings_client.py/blob/f232313a4237875cf7f719a631ff83e373b24e3a/biothings_client/base.py#L10

Got the following messages:

```
/usr/share/miniconda/lib/python3.8/site-packages/biothings_client/base.py:10
  /usr/share/miniconda/lib/python3.8/site-packages/biothings_client/base.py:10: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Iterable
```

Python 3.9 is [scheduled](https://www.python.org/dev/peps/pep-0596/#id4) for release on 2020-10-05.

**Comment by newgene** [comment]
thank you @tirkarthi for the pull request.
