### ISSUE TITLE
Specifying the fetch_all block size?

### ISSUE THREAD

**Issue by dhimmel** [biothings/biothings_client.py#14]
I'm interested in using `MyGeneInfo.query(..., fetch_all=True)`. Here's the fetch_all docs:

https://github.com/biothings/biothings_client.py/blob/f7b53d53a566eac4e8a9d8694b6d3865bacfeab8/biothings_client/base.py#L393-L396

Regarding "server requests are done in blocks of 1000", is it possible to control that number? I.e. set a parameter like `fetch_all_size`?

There are two reasons why I'm interested in this:

1. for testing, where I will only consume the first few results.

2. to prevent timeout. If we have to do a somewhat slow processing of results as we iterate through them, it's possible the following timeout could occur:
    > Each 1000 block of results must be yielded within 1 minute, otherwise the request will expire at server side. 

    Reducing the block size would speed up the time it takes to process each block.

**Comment by dhimmel** [comment]
I see the following:

https://github.com/biothings/biothings_client.py/blob/092e3ca51bb115dcae3bb0c98c9df4635262f4b9/biothings_client/__init__.py#L66-L68

Perhaps passing `_step=10` would achieve what I'm looking for?

**Comment by namespacestd0** [comment]
this does not solve the problem, it's hard coded in the backend to return results in a size of 1000, https://github.com/biothings/biothings.api/blob/f4cd5880033de12e57fe6fa09ac5388802888508/biothings/web/query/engine.py#L115, server provisioning is kept in mind that the service intends to return all requests in 1 minute. in case we cannot meet this service objective, for example, some service serve especially large documents, it's possible to change the setting here in the backend https://github.com/biothings/biothings.api/blob/f4cd5880033de12e57fe6fa09ac5388802888508/biothings/web/services/namespace.py#L110 with the parameter "ES_SCROLL_TIME". Fixing the scroll time and scroll size in the backend is a legacy behavior. It seems to work okay so far.
