### ISSUE TITLE
Use standard logging stream

### ISSUE THREAD

**Issue by namespacestd0** [biothings/biothings_client.py#16]
Many components use print statement regardless of the `verbose` value. Consider replacing them using standardized logging stream or raising customized exceptions unless there is a `verbose` parameter evaluating to `true`. Consider automatically configure the logging stream if not already configured to achieve a similar behavior as before. If it is desirable to add an additional debug/details stream, maybe this is helpful: https://github.com/elastic/elasticsearch-py/blob/208269a532ac6d8cf5aaa901b16410ba84cb4513/elasticsearch/connection/base.py#L41

**Comment by namespacestd0** [comment]
Next step:
https://github.com/biothings/biothings_client.py/blob/ec56cd80d845cf8a80d864c743374a8e08e84ca8/biothings_client/base.py#L40-L43

**Comment by newgene** [comment]
close this issue now as the implementation was merged. Further improvements will be done in a new issue and branch.
