### ISSUE TITLE
fields parameter not working as intended

### ISSUE THREAD

**Issue by iamjli** [biothings/biothings_client.py#18]
In this example: 
```
mg = get_client("gene")
mg.getgene(1017, 'name,symbol,refseq')
```
the result returns an unfiltered dictionary (which I won't post here since it's big)

**Comment by namespacestd0** [comment]
can you try `pip install -U biothings_client` and see if it works after an update?

**Comment by Dneems** [comment]
I am also experiencing this same issue, `pip install -U biothings_client` did not fix the problem.  Its as if the fields parameter is being ignored

**Comment by Dneems** [comment]
In fact, I'm not sure if its a complete fix but just removing the names keyword argument `fields` from this line 
https://github.com/biothings/biothings_client.py/blob/092ffa1e1e35fbee2c9b7eb5defbee160697e3d8/biothings_client/base.py#L347
seems to fix it for me.  
Is this open source? I am happy to contribute a PR

**Comment by namespacestd0** [comment]
Hi @Dneems, thank you for the feedback. Yes, it's an open source project, we are evaluating this ticket to understand how to best move forward. Meanwhile, you may certainly make a PR to suggest the fix you have in mind.

**Comment by namespacestd0** [comment]
@Dneems An update from our team, we have identified this issue and our PI will apply a fix soon. Thank you for letting us know about this. In the future, you're always welcome to make a PR alongside an issue.

**Comment by namespacestd0** [comment]
We have updated the package to resolve the issue. Please see https://pypi.org/project/biothings-client/0.2.6/
