### ISSUE TITLE
Add support for mydisease.info client

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_client.py#3]

**Comment by cyrus0824** [comment]
This is done, as of commit [1cc605656922d9c20b3249b90f2e8d1d70ce705a](https://github.com/biothings/biothings_client.py/commit/1cc605656922d9c20b3249b90f2e8d1d70ce705a)

**Comment by newgene** [comment]
Available in [biothings_client v0.2.0 release](https://pypi.org/project/biothings-client/) now.
