### ISSUE TITLE
Use doc_type key in metadata to generate client without having to specific biothings_type

### ISSUE THREAD

**Issue by sirloon** [biothings/biothings_client.py#6]
Currently, when pointing biothings_client to a specific Biothings API URL, we need to specify:

```
client = get_client("variant","http://pending.biothings.io/denovodb")
```

Metadata have recently been updated to include "doc_type" containing "variant", that is, the actually biothings type being returned by the API. See: http://pending.biothings.io/denovodb/metadata. Generating the client can then be:

```
client = get_client("http://pending.biothings.io/denovodb")
```

make biothings_type optional. By default, /metadata is assumed to be added to the end of the URL.

This improvement will allow to generate clients completely dynamically, without having to know anything but the URL.

**Comment by greg-k-taylor** [comment]
I think that this would be a great enhancement coupled with listing the API URL in configuration.

**Comment by sirloon** [comment]
note: "doc_type" will be renamed "biothings_type" in the future

**Comment by namespacestd0** [comment]
@sirloon when you mentioned
`client = get_client("variant","http://pending.biothings.io/denovodb")`
`client = get_client("http://pending.biothings.io/denovodb")`
did you mean
`client = get_client("variant",url="http://pending.biothings.io/denovodb")`
`client = get_client(url="http://pending.biothings.io/denovodb")`?

**Comment by sirloon** [comment]
@namespacestd0 yes, that's right, with the named param "url=", ie. we don't want to change the signature, just making the first arg "biothing_type" optional, default to None and in that case, determine biothing_type according to what's in /metadata

**Comment by namespacestd0** [comment]
Implemented in https://github.com/biothings/biothings_client.py/commit/29277aedcd4f254fbe3e5a88a443cfc994cddf94
