### ISSUE TITLE
Need a better user agent pattern for biothings_client.py

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_client.py#7]
default: biothings_client.py/<ver>
mygene: biothings_client.py/<ver> mygene
myvariant: biothings_client.py/<ver> myvariant
mychem: biothings_client.py/<ver> mychem
...

The relevant code here: https://github.com/biothings/biothings_client.py/blob/master/biothings_client/__init__.py#L68

**Comment by namespacestd0** [comment]
@newgene May I ask if the space between the specified user_agent string example is left intentionally? For instance, when you mentioned "biothings_client.py/ mygene", did you mean "biothings_client.py/mygene"? Double checking this because it seems to contradict with common practice I've observed.

**Comment by namespacestd0** [comment]
Basing on a common pattern:

> User-Agent: &lt;product&gt;/&lt;version&gt; (&lt;system-information&gt;) &lt;platform&gt; (&lt;platform-details&gt;)

I propose:

> biothings_client.py/&lt;release&gt; (&lt;os&gt;; python:&lt;version&gt;; &lt;python-packages&gt;) &lt;api&gt;/&lt;version&gt; (&lt;server-info&gt;) user_query/&lt;commit-hash&gt;

With all fields included, it could look like:

`biothings_client.py/0.2.0 (Linux x86_64; python:3.7.1; requests:2.3.0) mygene/v3 (es:7.1) user_query/825e27e` 

We can start with including the most useful fields, which looks like:

`biothings_client.py/0.2.0 (python:3.7.1) mygene/v3`

This way, we can be better informed:

- if continuing support with lower python versions is necessary
- which service is more popular to be accessed with this python client
...

**Comment by newgene** [comment]
Great! Let's starts with this:

```
biothings_client.py/0.2.0 (python:3.7.1: requests:2.3.0)
```

for `biothings_client.py` direct  calls.

```
biothings_client.py/0.2.0 (python:3.7.1: requests:2.3.0)  mygene.py/3.1.0
```

for calling from `mygene.py` (same for `myvariant.py`)

**Comment by namespacestd0** [comment]
Implemented in https://github.com/biothings/biothings_client.py/commit/092e3ca51bb115dcae3bb0c98c9df4635262f4b9
https://github.com/biothings/myvariant.py/commit/79e4fc70de98d4a8720c756aa414f63a0de964ed
https://github.com/biothings/mygene.py/commit/c5cedc9e0ff8181ead037fdb3230c4a1d3e17828
Existing automated tests passed.
