### ISSUE TITLE
query terms split on space when passed to querymany as a list.

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_client.py#8]
Reported from @mmayers12:

```
from biothings_client import get_client
mt = get_client('taxon')
result = mt.querymany(['Aspergillus parasiticus', 'Chlamydophila psittaci'], scopes=['scientific_name'])

print('\n\n',set([r['query'] for r in result]))
```

this result in:

```
querying 1-2...done.
Finished.
3 input query terms found dup hits:
    [('Aspergillus', 10), ('parasiticus', 10), ('psittaci', 10)]
Pass "returnall=True" to return complete lists of duplicate or missing query terms.


 {'Aspergillus', 'parasiticus', 'Chlamydophila', 'psittaci'}
```

The query terms should not be split on spaces.

**Comment by namespacestd0** [comment]
An attempted fix to quote individual query terms when joining by delimiters would produce the following output instead:

> querying 1-2...done.Finished.
> 1 input query terms found dup hits:        [('Aspergillus parasiticus', 9)]
> 1 input query terms found no hit:
>         ['Chlamydophila psittaci']
> Pass "returnall=True" to return complete lists of duplicate or missing query terms.
> 
> 
>  {'Aspergillus parasiticus', 'Chlamydophila psittaci'}

Need to confirm if the new result makes sense.
